blogproj/blogproj/blogapp/urls.py
from django.urls import path
from .import views

app_name='blogapp'

urlpatterns=[
    path('',views.BlogListView.as_view(),name='list'),
    path('<int:pk>/',views.BlogDetailView.as_view(),name='detail'),
    path('createaccount',views.createaccount,name='createaccount'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('createpost',views.createpost,name='createpost'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),
    path('profiles',views.profiles,name='profiles'),
    path('myprofile',views.myprofile,name='myprofile'),
    path('update/<int:pk>/',views.BlogUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.BlogDeleteView.as_view(),name='delete')
]

blogproj/blogproj/blogproj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from blogapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('blogapp/',include('blogapp.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogproj/blogproj/blogapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class user_model(models.Model):
    models.OneToOneField(User,on_delete=models.CASCADE)

    key=models.ForeignKey(User,on_delete=models.CASCADE,blank=True)
    secret_name=models.CharField(max_length=200)
    phone=models.PositiveIntegerField()

    def __str__(self):
        return self.secret_name
    
class post_model(models.Model):
    title=models.CharField(max_length=200)
    description=models.CharField(max_length=1000)
    image=models.FileField(upload_to='images/',blank=True)
    date=models.DateTimeField(blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True)

    def __str__(self):
        return self.title

blogproj/blogproj/blogapp/forms.py
from django import forms
from .models import user_model,post_model
from django.contrib.auth.models import User

class user_form(forms.ModelForm):
    username=forms.CharField(help_text=None)
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username','email','password')

class user_form1(forms.ModelForm):
    class Meta:
        model = user_model
        fields = ('secret_name','phone')

class post_form(forms.ModelForm):
    class Meta:
        model = post_model
        fields='__all__'



blogproj/blogproj/blogapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse
from .forms import user_form,user_form1,post_form
from .models import user_model,post_model,User
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
import datetime
from django.views.generic import UpdateView,DeleteView,DetailView,ListView
from django.urls import reverse_lazy

# Create your views here.
def index(request):
    models=post_model.objects.all()
    umodel=user_model.objects.all()
    model=[]
    for i in models:
        model=[i]+model
    return render(request,'index.html',{'model':model,'umodel':umodel})

def createaccount(request):
    if request.method == 'POST':
        user_formA=user_form(request.POST)
        user_formB=user_form1(request.POST)
        if user_formA.is_valid() and user_formB.is_valid():
            formA=user_formA.save()
            formA.set_password(formA.password)
            formA.save()
            formB=user_formB.save(commit=False)
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username,password=password)
            if user:
                if user.is_active:
                    login(request,user)
                    formB.key = request.user
                    formB.formA=formA
                    formB.save()
                    return HttpResponseRedirect(reverse('blogapp:dashboard'))
    else:
        user_formA=user_form()
        user_formB=user_form1()
    return render(request,'createaccount.html',{'user_formA':user_formA,'user_formB':user_formB})

def dashboard(request):
    model=user_model.objects.all()
    return render(request,'dashboard.html',{'model':model})

def createpost(request):
    if request.method == 'POST':
        form=post_form(request.POST,request.FILES)
        print(form)
        if form.is_valid():
            print(request.user)
            instance = form.save(commit=False)
            instance.user = request.user
            instance.date = datetime.datetime.now()
            instance.save()
        return redirect('blogapp:index')
    return render(request,'createpost.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            print(user)
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('blogapp:index'))
            else:
                return HttpResponse('User Not Active')
        else:
            return HttpResponse('Incorret Creds')

    return render(request,'login.html',)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blogapp:index'))

def profiles(request):
    data=User.objects.all()
    data1=user_model.objects.all()
    return render(request,'profiles.html',{'data':data,'data1':data1})

def myprofile(request):
    models=post_model.objects.all().filter(user=request.user)
    model=[]
    for i in models:
        model=[i]+model
    umodel=user_model.objects.all()
    return render(request,'myprofile.html',{'model':model,'umodel':umodel})

class BlogListView(ListView):
    context_object_name = 'mylist'
    model = post_model

class BlogDetailView(DetailView):
    context_object_name = 'post_models'
    model = post_model
    template_name = 'blogapp/post_model_detail.html'

class BlogUpdateView(UpdateView):
    context_object_name = 'post_models'
    fields = ['title','description']
    model = post_model

class BlogDeleteView(DeleteView):
    context_object_name = 'post_models'
    model = post_model 
    success_url = reverse_lazy('blogapp:myprofile')

blogproj/blogproj/blogapp/templates/blogapp/post_model_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>Do you want to delete {{ post_models.title }}...??</h1>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="delete">
        </form>
    </div>
</div>

{% endblock %}

blogproj/blogproj/blogapp/templates/blogapp/post_model_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <h2>{{ post_models.title }}</h2>
                        <p>{{ post_models.description }}</p>
                            {% if post_models.image %}
                                <img src="{{post_models.image.url}}" alt="no img">
                            {% endif %}
                        <p>{{ post_models.date }}</p>
                    <a class="btn btn-warning" href="{% url 'blogapp:update' pk=post_models.pk %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'blogapp:delete' pk=post_models.pk %}">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blogproj/blogproj/blogapp/templates/blogapp/post_model_form.html
{% extends 'base.html' %}

{% block content %}

{% if not form.instance.pk %}
    <h1>Add Post</h1>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" calss="btn btn-primary" value="Add">
    </form>
{% else %}
    <h1>Update Post</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Update"> 
    </form>
{% endif %}

{% endblock %}

blogproj/blogproj/blogapp/templates/blogapp/post_model_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <ul>
                {% for data in mylist %}
                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-body">
                            <h2><a href="{{data.id}}">{{ data.title }}</a></h2>
                            <p>{{ data.description }}</p>
                            {% if data.image %}
                                <img src="{{data.image.url}}" alt="no img">
                            {% endif %}
                            <p>{{ data.date }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

blogproj/blogproj/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}"><b><i>BLOGPOST</i></b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blogapp:profiles' %}">Profiles</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blogapp:list' %}">My Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blogapp:logout' %}">Logout</a>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
      </nav>
</body>
</html>
{% block content %}

{% endblock %}

blogproj/blogproj/templates/createaccount.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<h2 align="center">Create Account</h2>
<br>
<center>
    <form method="POST">
        {% csrf_token %}
        <table>
        {{user_formA.as_table}}
        {{user_formB.as_table}}
        </table>
        <br><br>
        <input type="submit" value="Create Account" class="btn btn-dark">
        <a href="{% url 'blogapp:index' %}" class="btn btn-dark">Back</a>
    </form>
</center>
{% endblock %}

blogproj/blogproj/templates/createpost.html
{% extends 'base.html' %}
{% block content %}
<br>
<h2 align="center"><b>Create Post</b></h2>
<form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <div class="container" style="position: relative; left: 350px;">
        <div class="jumbotron" >
            <div class="card w-50 mb-3" style="border: 0px;">
                <div class="card-body">
                    <div class="w-75 mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Title</label>
                        <input type="text" class="form-control" id="exampleFormControlInput1" name="title" placeholder="Title">
                    </div>
                    <div class="w-75 mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Description</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" name="description" rows="3"></textarea>
                    </div>
                    <div class="w-75 mb-3">
                        <label for="formFile" class="form-label">Image</label>
                        <input class="form-control" multiple type="file" name="image" id="formFile">
                    </div>
                    <div class="w-75 mb-3">
                        <input type="submit" value="Post" class="btn btn-outline-success">
                    </div>
                </div>
            </div>  
        </div>
    </div>
</form>

{% endblock %}

blogproj/blogproj/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
<br>
<h2 align="center"><b>Dashboard</b></h2>
<br>
<center>
<div class="card w-75 mb-3">
    <div class="card-body">
        <div class="container text-center">
            <div class="row">
              <div class="col">
                {% for i in model %}
                {% if user == i.key %}
                <h3>{{i.secret_name}}</h3>
                {% endif %}
                {% endfor %}
              </div>
              <div class="col">
              </div>
              <div class="col">
                <a href="{% url 'blogapp:createpost' %}" style="align-self: flex-end;" class="btn btn-outline-danger"><b>+</b></a>
              </div>
            </div>
        </div>
    </div>
</div>
</center>
{% endblock %}

blogproj/blogproj/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<br><br>
<h2 align="center" style="color: brown;">Welcome to Blog Post</h2>
<br>
<center><a href="{% url 'blogapp:dashboard' %}" class="btn btn-outline-success">Create Post</a></center>
<hr><br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            {% for i in model %}
            <div class="col-md-12">
                <div class="card card-body w-50" style="border: 0;">
                    <ul style="list-style-type: none;">
                        {% for j in umodel %}
                        {% if i.user == j.key %}
                        <li><h4 style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"><b>{{j.secret_name}}</b></h4></li>
                        {% endif %}
                        {% endfor %}
                        <li><h6 style="font-family: TimesNewRoman, Times New Roman, Times, Baskerville, Georgia, serif;">{{i.title}}</h6></li>
                        <li><p style="font-size:small; font-family:Courier New, Courier, Lucida Sans Typewriter, Lucida Typewriter, monospace;">{{i.description}}</p></li>
                        {% if i.image %}
                        <li><img src="{{ i.image.url }}" alt="no img" width="75%"></li>
                        {% endif %}
                        <li><p style="color: rgb(100, 100, 100); font-size:smaller;">{{i.date}}</p></li>
                    </ul>
                    
                </div>
                <hr><hr>
                <br>
            </div>
            
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<br><br>
<center>
<div class="container">
    <a href="{% url 'blogapp:login' %}" class="btn btn-outline-dark">Login</a><br><br>
    <h5>or</h5><br>
    <a href="{% url 'blogapp:createaccount' %}" class="btn btn-outline-dark">Create Account</a>
</div>
</center>
{% endif %}


{% endblock %}

blogproj/blogproj/templates/login.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<h2 align="center">Login</h2>
<br>
<center>
    <form method="POST">
        {% csrf_token %}
            <label for="">Username :</label>  <input type="text" name="username" id=""><br><br>
            <label for="">Password :</label>   <input type="password" name="password" id="">
            <br><br>
            <input type="submit" value="Login" class="btn btn-dark">
            <a href="{% url 'blogapp:index' %}" class="btn btn-dark">Back</a>
    </form>
</center>
{% endblock %}

blogproj/blogproj/templates/myprofile.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div class="row">
            {% for i in model %}
            <div class="col-md-12">
                <div class="card card-body w-50" style="border: 0;">
                    <ul style="list-style-type: none;">
                        {% for j in umodel %}
                        {% if i.user == j.key %}
                        <li><h4 style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"><b>{{j.secret_name}}</b></h4></li>
                        {% endif %}
                        {% endfor %}
                        <li><h6 style="font-family: TimesNewRoman, Times New Roman, Times, Baskerville, Georgia, serif;">{{i.title}}</h6></li>
                        <li><p style="font-size:small; font-family:Courier New, Courier, Lucida Sans Typewriter, Lucida Typewriter, monospace;">{{i.description}}</p></li>
                        {% if i.image %}
                        <li><img src="{{ i.image.url }}" alt="" width="75%"></li>
                        {% endif %}
                        <li><p style="color: rgb(100, 100, 100); font-size:smaller;">{{i.date}}</p></li>
                                <form method="POST">
                            {% csrf_token %}
                            <p><a class="btn btn-warning" href="{% url 'blogapp:update' pk=post_models.pk %}">Edit</a></p>
                        </form>                
                    </ul>
                </div>
                <br>
            </div>
            <hr><hr>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

blogproj/blogproj/templates/profiles.html
{% extends 'base.html' %}
{% block content %}
<h2 align="center" style="color: brown;">Profiles</h2>
<br><br>
<center>
    {% for i in data %}
    <div class="card w-25 mb-3">
        <div class="card-body">
            <div class="container text-center">
                <div class="row">
                  <div class="col">
                    <h3>{{i.username}}</h3>
                  </div>
                </div>               
            </div>
        </div>
    </div>
    {% endfor %}
</center>
{% endblock %}